export class Struttura {
    trasporti: object;
    posizione: object;
    servizi: object;
    wellness: object;
    lingue: object;
    contatti: object;
    accoglienza:object;
    cap: string;
    zona: string;
    comune: string;
    stelle: string;
    interno: string;
    localita: string;
    categoria: string;
    indirizzo: string;
    provincia: string;
    tipologia: string;
    giochiBimbi: boolean;
    altriServizi: string;
    denominazione: string;
    numeroCivico: string;
    animaliAmmessi: boolean;
    accessoDisabili: boolean;
    chiusuraTemporanea: boolean;
    dataUltimaModifica: string;
    tipologiaSecondaria: string;
    codiceIdentificativo: number;
    nuovaClassificazioneLr11: string;
}